from distutils.core import setup

setup(name='django-la-profiles',
      version='0.3',
      description='User-profile application for Django',
      long_description = open("README.rst").read(),      
      author='Daniel Greenfeld',
      license = "BSD",
      author_email='pydanny@gmail.com',
      url='http://www.github.com/cartwheelweb/django-la-profiles/',
      packages=['la_profiles'],
      classifiers=['Development Status :: 4 - Beta',
                   'Environment :: Web Environment',
                   'Framework :: Django',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: BSD License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python',
                   'Topic :: Utilities'],
      )
